# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY entrypoint.sh /app
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
RUN ["chmod", "+x", "/app/entrypoint.sh"]